spring:
  application:
    name: order-management-api
  datasource:
    url: jdbc:mysql://localhost:3306/order_management_data?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: root
    #driver-class-name: com.mysql.cj.jdbc.Driver
    pool:
      initial-size: 100
      max-size: 500
      max-idle-time: 30m
      validation-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
